# Generated by Django 3.1.7 on 2021-03-11 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertoken',
            old_name='user',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='usertoken',
            old_name='expires_in',
            new_name='expires_at',
        ),
    ]
