# Generated by Django 3.1.7 on 2021-03-11 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210312_0052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
